first_name: Mami
last_name: Ravaloarison

location: New York, USA
email: mravaloarison@gmail.com

cv_pdf: /assets/pdf/resume.pdf

github: mravaloarison
linkedin: mravaloarison

url: https://mravaloarison.github.io
baseurl:

about_me: |
    I'm a data analyst with a strong background in programming and software development. I love building software that feels like shortcuts, or smarter and more efficient approaches to problems, and I’m deeply curious about how data and new technologies can impact the world.

    While I was a student, I activelly participated in hackathons, and won over 12 awards across universities in the U.S. by building iOS and watchOS apps, web applications, desktop tools, and browser extensions. These experiences strengthened my problem-solving skills, collaboration, and ability to prototype ideas quickly.

    Currently, I'm a data analyst at my old school, where I recreate legacy dashboards in <a href="https://www.microsoft.com/en-us/power-platform/products/power-bi">Power BI</a>. In addition to analytics work, I build and maintain <a href="https://support.microsoft.com/en-us/sharepoint">SharePoint</a> sites for my department and was recently assigned to redesign the university’s library website using <a href="https://www.springshare.com/">SpringShare</a>’s LibGuides platform.

    This role has made me more serious about pursuing a career in data science and learn deeper foundations through graduate study.

    Outside of work, I love dogs, learning new songs on the piano, guitar, and bass, playing chess, and video games. I also try to consistently cook healthy meals and going to the gym, though I’m still working on making those habits stick!

sections:
    Education:
        - institution: Monroe University
          location: Bronx, New York
          url: https://www.monroeu.edu/
          area: Computer Information Systems
          studyType: Bachelor of Science (Magna Cum Laude)
          start_date: 2021
          end_date: 2025
          score: "3.7/4.0 GPA"
          minor: Mathematics

        - institution: Lycée Privé ACEEM
          location: Madagascar
          url: https://www.youtube.com/@aceemgroupe8437
          area: Scientific
          studyType: Baccalauréat
          start_date: 2015
          end_date: 2018

    Experience:
        - company: Office of Academic Records, Assessment, and Planning, Monroe University
          position: Junior Data Analyst
          location: New Rochelle, New York
          start_date: 2025
          end_date: ongoing
          highlights:
              - Recreating and Optimizing 100+ dashboards on PowerBI to help the university track student performance, retention, and graduation rates.
              - Built a SharePoint site for the ARAP department to streamline data sharing and collaboration among team members.
              - Updated the University's Library website using HTML, CSS, JavaScript and LibGuide platform to enhance user experience and accessibility.

        - company: Student Success Center, Monroe University
          position: Information Technology Peer Tutor
          location: Bronx, New York
          start_date: 2023
          end_date: 2025
          highlights:
              - Tutored students in Excel, databases, and Programming across multiple academic levels.
              - Assisted alumni with real-world IT issues, including e-commerce website setup and troubleshooting.

        - company: New Rochelle Council of Community Services
          position: Software Developer Intern
          location: New Rochelle, New York
          start_date: 2023
          end_date: 2023
          highlights:
              - Collaborated with a team to redesign the nonprofit's website using Next.js (TypeScript) and Tailwind CSS.
              - Implemented Figma wireframes into functional interfaces and recreated designs using WordPress theme and plugins.

        - company: Residence Life, Monroe University
          position: Resident Assistant
          location: New Rochelle, New York
          start_date: 2022
          end_date: 2023
          highlights:
              - Supported 50+ dorm rooms by resolving conflicts, reporting maintenance issues, and providing resources to students.
              - Planned and led 10+ events per semester while collaborating with fellow RAs and Residence life staff to promote community engagement.

    Awards:
        - title: 12 Hackathon wins
          date: 2022-2024
          awarder: Several East Coast Universities & Major League Hacking
          url: https://devpost.com/mrava
          summary: 12 Hackathon wins across the U.S. (Yale, Princeton, Stony Brook, RPI, University of Penn), earning ~$4,000 in prizes.

        - title: Dean's Award for Academic Excellence
          date: 2025
          awarder: Monroe University
          summary: Awarded for outstanding academic achievement, leadership and impact.

    Languages:
        - name: Malagasy
          summary: "Native speaker"

        - name: English
          summary: "Fluent"

        - name: French
          summary: "Fluent (DELF B2 Certified)"

    Interests:
        - name: Applied AI & Data Systems
          icon: bi-tag
          keywords: "Machine Learning, Deep Learning, Data Analysis, Data Visualization, Big Data, Data Engineering, MCP, RAG"

    Certificates:
        - name: CS50P - Introduction to Programming with Python
          date: 2022
          issuer: Harvard University
          icon: bi-tag

        - name: DELF B2 - French Language Proficiency
          date: 2020
          issuer: Alliance Française Madagascar
          icon: bi-tag

# BLOG CONFIGURATION
blog_description: >
    This is just a space where I write about whatever I’m thinking through, my honest thoughts on different subjects.

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
    - jekyll-paginate
