first_name: Mami
last_name: Ravaloarison

location: New York, USA
email: mravaloarison@gmail.com

cv_pdf: /assets/pdf/resume.pdf

github: mravaloarison
linkedin: mravaloarison

url: https://mravaloarison.github.io
baseurl:
